package com.lionxxw.employee.entity;

import java.util.Date;

public class EmpDepView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.account
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.pwd
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.name
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.sex
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.mobile
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.email
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.is_manager
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private Boolean isManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.create_time
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.state
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.dep_id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.dep_name
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_dep_view.parent_dep_Id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    private Long parentDepId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.id
     *
     * @return the value of emp_dep_view.id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.id
     *
     * @param id the value for emp_dep_view.id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.account
     *
     * @return the value of emp_dep_view.account
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.account
     *
     * @param account the value for emp_dep_view.account
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.pwd
     *
     * @return the value of emp_dep_view.pwd
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.pwd
     *
     * @param pwd the value for emp_dep_view.pwd
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.name
     *
     * @return the value of emp_dep_view.name
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.name
     *
     * @param name the value for emp_dep_view.name
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.sex
     *
     * @return the value of emp_dep_view.sex
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.sex
     *
     * @param sex the value for emp_dep_view.sex
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.mobile
     *
     * @return the value of emp_dep_view.mobile
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.mobile
     *
     * @param mobile the value for emp_dep_view.mobile
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.email
     *
     * @return the value of emp_dep_view.email
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.email
     *
     * @param email the value for emp_dep_view.email
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.is_manager
     *
     * @return the value of emp_dep_view.is_manager
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public Boolean getIsManager() {
        return isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.is_manager
     *
     * @param isManager the value for emp_dep_view.is_manager
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setIsManager(Boolean isManager) {
        this.isManager = isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.create_time
     *
     * @return the value of emp_dep_view.create_time
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.create_time
     *
     * @param createTime the value for emp_dep_view.create_time
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.state
     *
     * @return the value of emp_dep_view.state
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.state
     *
     * @param state the value for emp_dep_view.state
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.dep_id
     *
     * @return the value of emp_dep_view.dep_id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.dep_id
     *
     * @param depId the value for emp_dep_view.dep_id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.dep_name
     *
     * @return the value of emp_dep_view.dep_name
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.dep_name
     *
     * @param depName the value for emp_dep_view.dep_name
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_dep_view.parent_dep_Id
     *
     * @return the value of emp_dep_view.parent_dep_Id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public Long getParentDepId() {
        return parentDepId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_dep_view.parent_dep_Id
     *
     * @param parentDepId the value for emp_dep_view.parent_dep_Id
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    public void setParentDepId(Long parentDepId) {
        this.parentDepId = parentDepId;
    }
}