package com.lionxxw.employee.entity;

import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.account
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.pwd
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.mobile
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.is_manager
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private Boolean isManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.create_time
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.state
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.account
     *
     * @return the value of employee.account
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.account
     *
     * @param account the value for employee.account
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.pwd
     *
     * @return the value of employee.pwd
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.pwd
     *
     * @param pwd the value for employee.pwd
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sex
     *
     * @return the value of employee.sex
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sex
     *
     * @param sex the value for employee.sex
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.mobile
     *
     * @return the value of employee.mobile
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.mobile
     *
     * @param mobile the value for employee.mobile
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.is_manager
     *
     * @return the value of employee.is_manager
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public Boolean getIsManager() {
        return isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.is_manager
     *
     * @param isManager the value for employee.is_manager
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setIsManager(Boolean isManager) {
        this.isManager = isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.create_time
     *
     * @return the value of employee.create_time
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.create_time
     *
     * @param createTime the value for employee.create_time
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.state
     *
     * @return the value of employee.state
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.state
     *
     * @param state the value for employee.state
     *
     * @mbggenerated Tue May 10 12:56:35 CST 2016
     */
    public void setState(Integer state) {
        this.state = state;
    }
}