package com.lionxxw.employee.mapper;

import com.lionxxw.employee.entity.EmpDepView;
import com.lionxxw.employee.entity.EmpDepViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpDepViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_dep_view
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    int countByExample(EmpDepViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_dep_view
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    int deleteByExample(EmpDepViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_dep_view
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    int insert(EmpDepView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_dep_view
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    int insertSelective(EmpDepView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_dep_view
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    List<EmpDepView> selectByExample(EmpDepViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_dep_view
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") EmpDepView record, @Param("example") EmpDepViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_dep_view
     *
     * @mbggenerated Tue May 10 13:40:07 CST 2016
     */
    int updateByExample(@Param("record") EmpDepView record, @Param("example") EmpDepViewExample example);
}